"use client";

import Link from "next/link";
import { Sparkles, Shield, ChevronLeft } from "lucide-react";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-black text-white relative flex flex-col">
            <div className="absolute inset-0 [background-image:linear-gradient(to_right,rgba(255,255,255,0.05)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,0.05)_1px,transparent_1px)] bg-[length:40px_40px]"></div>

            <nav className="relative z-10 px-6 py-8 border-b border-white/5 bg-black/50 backdrop-blur-md">
                <div className="max-w-7xl mx-auto flex justify-between items-center">
                    <Link href="/" className="flex items-center space-x-2">
                        <Sparkles className="h-6 w-6 text-purple-400" />
                        <h1 className="text-2xl font-bold bg-gradient-to-r from-purple-400 to-blue-500 bg-clip-text text-transparent">
                            QuickLearn.ai
                        </h1>
                    </Link>
                    <Link href="/" className="text-gray-400 hover:text-white transition-colors flex items-center gap-2 text-sm">
                        <ChevronLeft size={16} /> Back to Home
                    </Link>
                </div>
            </nav>

            <main className="relative z-10 flex-grow max-w-4xl mx-auto px-6 py-16">
                <div className="flex items-center gap-4 mb-8">
                    <div className="w-12 h-12 bg-purple-900/20 rounded-2xl flex items-center justify-center border border-purple-500/20">
                        <Shield className="text-purple-400" />
                    </div>
                    <h2 className="text-4xl font-bold text-white">Terms of Service</h2>
                </div>

                <div className="space-y-12 text-gray-300 font-light leading-relaxed">
                    <section>
                        <h3 className="text-xl font-semibold text-white mb-4">1. Acceptance of Terms</h3>
                        <p>
                            By accessing and using QuickLearn.ai, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.
                        </p>
                    </section>

                    <section>
                        <h3 className="text-xl font-semibold text-white mb-4">2. Description of Service</h3>
                        <p>
                            QuickLearn.ai is an AI-powered educational platform that provides explanations and video recommendations. These explanations are generated by artificial intelligence and should be verified for critical educational needs.
                        </p>
                    </section>

                    <section>
                        <h3 className="text-xl font-semibold text-white mb-4">3. User Conduct</h3>
                        <p>
                            Users agree to use the service for lawful educational purposes only. Any attempt to disrupt the service, scrape data without permission, or use the generated content for academic dishonesty is strictly prohibited.
                        </p>
                    </section>

                    <section>
                        <h3 className="text-xl font-semibold text-white mb-4">4. Intellectual Property</h3>
                        <p>
                            The platform architecture, design, and original content are the property of QuickLearn.ai. AI-generated explanations are provided for personal educational use.
                        </p>
                    </section>
                </div>
            </main>

            <footer className="relative z-10 py-12 border-t border-white/5 text-center text-gray-500 text-sm">
                <p>© 2024 QuickLearn.ai. All rights reserved.</p>
            </footer>
        </div>
    );
}
